version: '2'
services:
    proxima-app:
        image: proxima
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://proxima-mysql:3306/proxima?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    proxima-mysql:
        extends:
            file: mysql.yml
            service: proxima-mysql
